repos:
-   repo: https://git.afpy.org/AFPy/powrap
    rev: v1.0.2
    hooks:
    -   id: powrap
-   repo: local
    hooks:
    -   id: check-spell
        name: Check spelling
        entry: python ./scripts/check_spell.py
        language: python
        additional_dependencies: ['pospell>=1.1']
        files: \.po$
    -   id: lint
        name: Run sphinx linting
        entry: sphinx-lint
        language: python
        additional_dependencies: ['sphinx-lint==0.6.7']
        files: \.po$
